- .github/workflows/ClearTodaySalt.yml
AWS로 마이그레이션 하기 위해서 워크플로에 ssh 연결을 추가하였습니다.
> 🔀::AWS 마이그레이션을 위한 워크플로 수정

- src/repositories/SaltRepository.ts
사용하지 않는 함수를 제거하였습니다.
SaltRepository에서 구현하지 않은 함수를 제거하였습니다.
> 🔀::사용하지 않는 함수 제거

- .github/CODEOWNERS
> 🔀::codeowner 설정 추가

- .github/workflows/deployAws.yml
> 💚 :: actions/checkout 버전 변경 및 테스트

- .github/workflows/deployAws.yml
> 💚 :: 배포 시 pull 하도록 변경

- .github/workflows/deployAws.yml
> 🔀 :: 배포 시 pull 할 브랜치 변경

- src/commands/FilterMensionCommand.ts
- src/discordClient.ts
> 🔀 :: 인터렉션 필터 수정

- src/commands/FilterMensionCommand.ts
> 🐛 :: 인터렉션 실시간으로 가져오도록 변경

- src/commands/FilterMensionCommand.ts
/mention 명령어에서 멤버 목록을 받아오지 못했을 때의 예외 처리
> 🔀 멘션 필터링 기능 예외 처리

- package.json
- src/MSGSaltBot.ts
- src/index.ts
- src/interfaces/Job.ts
- src/services/JobService.ts
일정 주기마다 돌리는 Job을 실행할 수 있는 환경 구축
> 🔀  :: Job Service 환경 추가

- src/commands/FetchScheduleListCommand.ts
현재 등록되어있는 일정 리스트를 보여주는 Command 추가
- 등록된 일정들을 보여주는 command 추가
> 🔀 :: 등록된 일정 리스트 Command

- src/commands/DeleteScheduleCommand.ts
일정을 삭제하는 Command 추가
일정의 ID를 받아 삭제하는 Command 추가
> 🔀  :: 일정 삭제 Command 추가

- src/commands/SyncScheduleCommand.ts
일정 동기화 Command 추가
캐시에 저장된 Schedule과 원격(Firestore)의 정보를 동기화하는 Command 추가
> 🔀  :: 일정 동기화 Command 추가

- src/jobs/ReminderSchedulerJob.ts
일정 리마인더를 수행하는 Job 추가
- 일정이 시작되기 15분전인 일정들을 리마인더해주는 Job 추가
- DM으로 각자에게 전달하여 참여 여부 답할 수 있는 기능 추가
> 🔀 : :: 일정 리마인더 Job 추가

- package.json
- src/jobs/SchedulerJob.ts
일정의 알림을 보내는 Job 추가
- 일정 별로 시간이 되었을때 채널에 알림을 보내는 기능을 수행하는 Job 추가
- 일정에 늦은 사람을 선택할 시 DM으로 대신 불러주는 기능 작업
> 🔀 : :: 일정 알림 Job 추가

- src/jobs/TodayScheduleJob.ts
오늘 잡혀있는 일정을 보내주는 Job 추가
- 매일 오전 8시에 오늘 잡혀있는 일정을 보내주는 Job 추가
> 🔀 :: 오늘 잡혀있는 일정을 보내주는 Job 추가

- src/index.ts
오늘 일정에 대해서 알려주는 Job을 등록해요
- TodayScheduleJob 등록
> 🔀 :: 오늘 일정 알림 Job 등록

- src/jobs/SchedulerJob.ts
> ♻️ 회의에 늦은 팀원 부르기 유효기간 15분으로 늘리기

- src/commands/AddScheduleCommand.ts
> 🔀 :: 일정 생성 입력 유효기간 1분 -> 5분

- package.json
- pnpm-lock.yaml
- src/commands/AddScheduleCommand.ts
luxon is gone, hello dayjs
년도를 안 받으면 현재 년도로 설정함
> 년도를 안 받으면 현재 년도로 설정함

- src/commands/AddScheduleCommand.ts
기존의 날짜 입력 안내 메시지가 너무 복잡해서 변경했어요
날짜 입력 안내 메시지 변경
> 🔁 날짜 입력 안내 메시지 변경

- src/jobs/TodayScheduleJob.ts
소금이의 존재감 어필을 위해 하루마다 채널에도 오늘의 일정을 뿌려줘요
Resolves: ㅎㅎ;
- 소금이의 존재감 어필과 리마인더 효과를 위해 하루마다 채널에도 오늘 있을 일정도 보내주어요!
> 🔀 :: 채널에도 오늘의 일정 뿌려주기

- src/commands/AddScheduleCommand.ts
년도를 지정하지 않는 경우 2001년으로 지정되는 문제를 해결했습니다
03-27 -> 2024-03-27
Resolves: #49
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!
> 🔁 년도가 지정되지 않은 경우 새로운 년도를 지정
